services:
  - type: web
    name: libretranslate
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      rm -rf *.egg-info
      rm -rf build dist
      pip install --no-cache-dir wheel setuptools
      pip install --no-cache-dir -r requirements.txt
      pip install --no-cache-dir .
    startCommand: libretranslate --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DISABLE_POETRY
        value: "1"
      - key: PORT
        value: "5000"
    plan: free
    memoryLimit: 1024 