services:
  - type: web
    name: libretranslate
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11 